### ISSUE TITLE
Do we have a design spec for 'muted header'?

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-brochure-theme#10]
This is used in the vf.io design but I can't remember talking about in the brochure theme workshop?

https://www.dropbox.com/s/hjupuyymmtahjma/Screenshot%202017-01-13%2017.04.34.png?dl=0

**Comment by anthonydillon** [comment]
Current spec is:
```css
.muted-heading {
    font-size: .875em; // 14px
    margin-bottom: 20px;
    text-align: center;
    text-transform: uppercase;
}
```

I would argue that we could remove the text centring and only style the text for this component. We have a utility class to centre text if we need it.
