### ISSUE TITLE
Create .strip--accent variant

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-brochure-theme#8]
![strip--accent](https://cloud.githubusercontent.com/assets/505570/21898750/c2f6043c-d8e5-11e6-8f89-d7add7669ad7.jpg)

This should be set using theme global variable.

**Comment by anthonydillon** [comment]
Would this work as the spec?

```css
.strip--accent {
  @include %strip;
  background: $color-accent;
  color: $color-accent-text;
```

Two points here:
- **background** would allow the user to set there accent variable as a image. For example; `$color-accent = url(image.png) no-repeat`. This does make the variable name nonsensical.
- **color** would need to change to adapt to the background. If we accommodate images then I believe this requires a second complementary variable to set the text colour. Which could be a accent map.

**Comment by yaili** [comment]
Why should we accommodate images?

**Comment by anthonydillon** [comment]
The examples we have also contain images but once we have the image-strip that will cover that pattern. We should just use the `$colour-accent` and check its lightness to select the text colour.

```scss
@function determine-text-color($background-color) {
  @if (lightness($background-color) > 50) {
    @return $color-mid-dark;
  } @else {
    @return $color-x-light;
  }
}

.strip--accent {
  @include %strip;
  background-color: $color-accent;
  color: determine-text-color($notification-confirm);
}
```
